 var resData = {
               "score":  72 ,    
                "issueNum":  0 ,   
                "gotest":"{\"summary\":{\"code_cover\":60.1,\"pkg_cover\":0.9,\"total_time\":38.4},\"content\":{\"pkg\":[\"github.com/wgliang/logcool/filter/metrics\",\"github.com/wgliang/logcool/filter/zeus\",\"github.com/wgliang/logcool/output/redis\",\"github.com/wgliang/logcool/filter/grok\",\"github.com/wgliang/logcool/input/http\",\"github.com/wgliang/logcool/output/stdout\",\"github.com/wgliang/logcool/input/stdin\",\"github.com/wgliang/logcool/output/lexec\",\"github.com/wgliang/logcool/input/file\",\"github.com/wgliang/logcool/cmd\",\"github.com/wgliang/logcool/filter/split\",\"github.com/wgliang/logcool/output/email\"],\"cover\":[88.2,83.3,28.2,80,81.1,81.8,75,80,9.5,58,92.3,84],\"time\":[1.03,1.028,1.033,1.028,2.031,6.034,6.027,6.03,6.028,1.036,1.028,6.033],\"no_test\":[\"github.com/wgliang/logcool/utils\",\"github.com/wgliang/logcool/input/collectd\"]}}",
                
                codeStyle: "{\"summary\":{\"issue_num\":135,\"file_num\":134,\"quality\":\"\"},\"content\":{\"go_fmt\":{\"label\":\"\",\"score\":0,\"detail\":null},\"go_vet\":{\"label\":\"\",\"score\":0,\"detail\":null},\"go_lint\":{\"label\":\"\",\"score\":0,\"detail\":null},\"miss_spell\":{\"label\":\"Correct commonly misspelled English words... quickly\",\"score\":0,\"detail\":[{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/net/net_darwin_test.go:33\",\"content\":[\" TestparseNetstatLineHeader has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/net/net_darwin_test.go:51\",\"content\":[\" TestparseNetstatLineLink has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/net/net_darwin_test.go:60\",\"content\":[\" TestparseNetstatLineIPv6 has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/net/net_darwin_test.go:68\",\"content\":[\" TestparseNetstatLineIPv4 has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/internal/common/common_test.go:51\",\"content\":[\" TestmustParseInt32 has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/internal/common/common_test.go:57\",\"content\":[\" TestmustParseUint64 has malformed name: first letter after 'Test' must not be lowercase\"]},{\"file\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/vendor/github.com/shirou/gopsutil/internal/common/common_test.go:63\",\"content\":[\" TestmustParseFloat64 has malformed name: first letter after 'Test' must not be lowercase\"]}]}}}",
                
                goIssue: "{\"summary\":{\"issue_num\":0,\"file_num\":0,\"quality\":\"\"},\"content\":{\"dead_code\":{\"label\":\"Unused code.\",\"score\":0,\"detail\":null},\"simple_code\":{\"label\":\"gosimple is a linter for Go source code that specialises on simplifying code.\",\"score\":0,\"detail\":null},\"static_code\":{\"label\":\"\",\"score\":0,\"detail\":null},\"copy_code\":{\"label\":\"Find code clones. So far it can find clones only in the Go source files. The method uses suffix tree for serialized ASTs. It ignores values of AST nodes.\",\"score\":0,\"detail\":null},\"interfacer_code\":{\"label\":\"A linter that suggests interface types. In other words, it warns about the usage of types that are more specific than necessary.\",\"score\":0,\"detail\":null}}}",
                
                countCode: "{\"summary\":{\"line_count\":2719,\"comment_count\":176,\"function_count\":0,\"file_count\":39},\"content\":{\"pkg\":null,\"pkg_line_count\":null,\"pkg_comment_count\":null,\"pkg_function_count\":null,\"file\":null,\"file_line_count\":null,\"file_comment_count\":null,\"file_function_count\":null}}",
                
                codeSmell: "{\"summary\":{\"issue_num\":1,\"file_num\":1,\"quality\":\"\"},\"content\":{\"percentage\":{\"1-15\":172,\"15-50\":1,\"50-\":0},\"pkg\":[\"github.com/wgliang/logcool/output/email\",\"github.com/wgliang/logcool/input/http\",\"github.com/wgliang/logcool/filter/zeus\",\"github.com/wgliang/logcool/input/file\",\"github.com/wgliang/logcool/cmd\",\"github.com/wgliang/logcool/filter/grok\",\"github.com/wgliang/logcool\",\"github.com/wgliang/logcool/input/stdin\",\"github.com/wgliang/logcool/utils\",\"github.com/wgliang/logcool/utils/logo\",\"github.com/wgliang/logcool/filter/metrics\",\"github.com/wgliang/logcool/output/lexec\",\"github.com/wgliang/logcool/filter/split\",\"github.com/wgliang/logcool/output/stdout\",\"github.com/wgliang/logcool/input/collectd\",\"github.com/wgliang/logcool/output/redis\"],\"cyclo\":[1,2,1,4,2,2,8,2,2,1,2,1,1,1,1,2],\"list\":[{\"path\":\"/Users/wangguoliang/Documents/wgliang/src/github.com/wgliang/logcool/input/file/file.go:222:1\",\"cyclo\":17}]}}"  
            }